#!/bin/sh
# postrm script for bunsen-faenza-icon-theme

set -e

START_HERE_ALT_DIR='/usr/share/icons/gnome/scalable/places'

case $1 in
remove|deconfigure)
    if ! dpkg -S "$START_HERE_ALT_DIR" >/dev/null 2>&1 \
    && [ -d "$START_HERE_ALT_DIR" ] \
    && which rmdir >/dev/null
    then
        rmdir --ignore-fail-on-non-empty "$START_HERE_ALT_DIR" || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
